// Generate the typed command client from the Rust surface.
//
// `crates/everyday-service/surface.json` is written by a Rust test and is the
// wire: every command, the scope it needs, what it takes and what it gives
// back. This turns it into TypeScript, so that renaming an argument in Rust is
// a type error here rather than a call that silently sends `undefined`.
//
// What it does *not* generate is the record types -- `Entry`, `Task`, `Item`.
// Those stay hand-written in `types.ts`, and this file only references them.
// Deriving them would mean a JSON-schema implementation on every type in the
// core, which is a large dependency in a crate that is deliberately small; the
// drift that actually bites is in the *call*, and that is what this covers.
//
//   npm --prefix ui run gen:api
//
// The output is committed, so a change to either side shows up in review.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..', '..')
const surface = JSON.parse(
  readFileSync(join(root, 'crates', 'everyday-service', 'surface.json'), 'utf8'),
)
const typesSource = readFileSync(join(here, '..', 'src', 'lib', 'types.ts'), 'utf8')

/** Names TypeScript already has, so they are never imported. */
const BUILTIN = new Set(['string', 'number', 'boolean', 'void', 'unknown', 'null', 'undefined'])

/** Every type `types.ts` exports, so an unknown one is caught here. */
const declared = new Set(
  [...typesSource.matchAll(/^export (?:type|interface|const enum) (\w+)/gm)].map((m) => m[1]),
)

/** The identifiers inside a type expression such as `Task[] | null`. */
function referenced(expr) {
  return [...expr.matchAll(/[A-Za-z_]\w*/g)].map((m) => m[0]).filter((name) => !BUILTIN.has(name))
}

const needed = new Set()
const unknownTypes = new Map()
for (const command of surface.commands) {
  for (const expr of [...command.args.map((a) => a.type), command.returns]) {
    for (const name of referenced(expr)) {
      if (declared.has(name)) needed.add(name)
      else unknownTypes.set(name, command.name)
    }
  }
}

if (unknownTypes.size > 0) {
  const lines = [...unknownTypes].map(([type, cmd]) => `  ${type}  (used by ${cmd})`)
  console.error(
    `gen-api: these types are on the wire but not exported from ui/src/lib/types.ts:\n` +
      lines.join('\n') +
      `\n\nAdd them there, or correct the signature in the Rust command table.`,
  )
  process.exit(1)
}

/** `save_entry` -> `saveEntry`, for a client that reads like a method. */
const camel = (name) => name.replace(/_(\w)/g, (_, c) => c.toUpperCase())

const argsType = (command) =>
  command.args.length === 0
    ? 'Record<string, never>'
    : `{ ${command.args.map((a) => `${a.name}${a.required ? '' : '?'}: ${a.type}`).join('; ')} }`

const sorted = [...surface.commands].sort((a, b) => a.name.localeCompare(b.name))
const writes = sorted.filter((c) => c.effect !== 'read')

const out = `// GENERATED by ui/scripts/gen-api.mjs. Do not edit.
//
// Source: crates/everyday-service/surface.json, which a Rust test writes from
// the command table. To change anything here, change the Rust and run:
//
//   UPDATE_SURFACE=1 cargo test -p everyday-service --test surface
//   npm --prefix ui run gen:api

import type {
${[...needed]
  .sort()
  .map((n) => `  ${n},`)
  .join('\n')}
} from '../types'

/** The command surface this build of the interface was generated against. */
export const PROTOCOL = ${surface.protocol}

/** What each command takes and gives back. */
export interface Commands {
${sorted
  .map((c) => `  ${camel(c.name)}: { args: ${argsType(c)}; result: ${c.returns} }`)
  .join('\n')}
}

/** The name each method sends over the wire. */
export const COMMAND_NAMES = {
${sorted.map((c) => `  ${camel(c.name)}: '${c.name}',`).join('\n')}
} as const

/**
 * Commands that go through the generic \`call\`.
 *
 * Anything else \`invoke\` is given is called by name: the shell's own --
 * opening a vault, the tray, the raw attachment body -- and the streaming ones,
 * which answer with a channel rather than a value and so have a command of
 * their own on the shell.
 *
 * Derived rather than listed, so the by-name set is whatever is left over and
 * cannot drift out of step with the Rust.
 */
export const SERVICE_COMMANDS: ReadonlySet<string> = new Set([
${sorted
  .filter((c) => !c.streams)
  .map((c) => `  '${c.name}',`)
  .join('\n')}
])

/**
 * Commands that change something, and so carry a request id.
 *
 * The id is what lets a retry over a dropped connection be answered from the
 * first attempt instead of being refused as a conflict against itself. See
 * \`everyday_service::idempotency\`.
 */
export const WRITE_COMMANDS: ReadonlySet<string> = new Set([
${writes.map((c) => `  '${c.name}',`).join('\n')}
])

/** What a listener should reload after a command succeeds. */
export const CHANGE_KINDS = {
${sorted
  .filter((c) => c.changes)
  .map((c) => `  ${c.name}: '${c.changes.kind}',`)
  .join('\n')}
} as const

/**
 * What a change touched, for \`live.svelte.ts\` and everything else that
 * routes on it.
 *
 * Derived from \`CHANGE_KINDS\` above rather than listed a second time by hand
 * -- the hand-written union in \`types.ts\` used to be the one place this could
 * fall out of step with the Rust, since nothing checked that every kind a
 * command could emit was still spelled out there. \`types.ts\` re-exports this
 * so nothing that already imports \`ChangeKind\` from there has to change.
 */
export type ChangeKind = (typeof CHANGE_KINDS)[keyof typeof CHANGE_KINDS]
`

mkdirSync(join(here, '..', 'src', 'lib', 'generated'), { recursive: true })
writeFileSync(join(here, '..', 'src', 'lib', 'generated', 'commands.ts'), out)
console.log(`gen-api: ${sorted.length} commands -> ui/src/lib/generated/commands.ts`)
